/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class TabelaHash {

    private Map<Integer, String> alunos;

    public TabelaHash(){
        alunos = new HashMap<Integer,String>();
        this.montarListaChamada();
    }

    public void montarListaChamada(){
        alunos.put(341234, "Joao");
        alunos.put(245234, "Maria");
        alunos.put(1234123, "Jose");
        alunos.put(67853, "Ana");
    }

    public Map<Integer, String> getAlunos() {
        return alunos;
    }

    public Set<Integer> getChaves(){
        return this.alunos.keySet();
    }

    public Collection<String> getValores(){
        return this.alunos.values();
    }


    public static void main(String[] args) {

        TabelaHash tabela = new TabelaHash();

        Map<Integer, String> alunos = tabela.getAlunos();

//        System.out.println("Alunos: " + alunos);

        System.out.println(alunos.containsValue("Mario"));
//        System.out.println("Valor: " + alunos.get(245234234));

//        for(String nome: tabela.getValores()){
//            System.out.println("> " + nome);
//        }

//        Set<Integer> chaves = tabela.getChaves();
//        for (Integer id : chaves) {
//            System.out.println("> " + id);
//        }

    }
}
